// automatically generated by the FlatBuffers compiler, do not modify

package ai.rapids.spark.format;

public final class CodecType {
  private CodecType() { }
  /**
   * no compression codec was used on the data
   */
  public static final byte UNCOMPRESSED = 0;

  public static final String[] names = { "UNCOMPRESSED", };

  public static String name(int e) { return names[e]; }
}

