/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nvidia_spark_ml_linalg_JniCUBLAS */

#ifndef _Included_com_nvidia_spark_ml_linalg_JniCUBLAS
#define _Included_com_nvidia_spark_ml_linalg_JniCUBLAS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nvidia_spark_ml_linalg_JniCUBLAS
 * Method:    dspr
 * Signature: (ID[DI[D)V
 */
JNIEXPORT void JNICALL Java_com_nvidia_spark_ml_linalg_JniCUBLAS_dspr
  (JNIEnv *, jobject, jint, jdouble, jdoubleArray, jint, jdoubleArray);

/*
 * Class:     com_nvidia_spark_ml_linalg_JniCUBLAS
 * Method:    dgemm
 * Signature: (III[[D[[D)V
 */
JNIEXPORT void JNICALL Java_com_nvidia_spark_ml_linalg_JniCUBLAS_dgemm
  (JNIEnv *, jobject, jint, jint, jint, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
