/*
 * Copyright (c) 2026, NVIDIA CORPORATION.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// automatically generated by the FlatBuffers compiler, do not modify

package com.nvidia.spark.rapids.format;

public final class CodecType {
  private CodecType() { }
  /**
   * data simply copied, codec is only for testing
   */
  public static final byte COPY = -1;
  /**
   * no compression codec was used on the data
   */
  public static final byte UNCOMPRESSED = 0;
  /**
   * data compressed with the nvcomp LZ4 codec
   */
  public static final byte NVCOMP_LZ4 = 1;
  /**
   * data compressed with the nvcomp ZSTD codec
   */
  public static final byte NVCOMP_ZSTD = 2;

  public static final String[] names = { "COPY", "UNCOMPRESSED", "NVCOMP_LZ4", "NVCOMP_ZSTD", };

  public static String name(int e) { return names[e - COPY]; }
}
