// automatically generated by the FlatBuffers compiler, do not modify

package ai.rapids.spark.format;

public final class SerializedDType {
  private SerializedDType() { }
  public static final int INVALID = 0;
  public static final int INT8 = 1;
  public static final int INT16 = 2;
  public static final int INT32 = 3;
  public static final int INT64 = 4;
  public static final int FLOAT32 = 5;
  public static final int FLOAT64 = 6;
  public static final int BOOL8 = 7;
  public static final int TIMESTAMP_DAYS = 8;
  public static final int TIMESTAMP_SECONDS = 9;
  public static final int TIMESTAMP_MILLISECONDS = 10;
  public static final int TIMESTAMP_MICROSECONDS = 11;
  public static final int TIMESTAMP_NANOSECONDS = 12;
  public static final int CATEGORY = 13;
  public static final int STRING = 14;

  public static final String[] names = { "INVALID", "INT8", "INT16", "INT32", "INT64", "FLOAT32", "FLOAT64", "BOOL8", "TIMESTAMP_DAYS", "TIMESTAMP_SECONDS", "TIMESTAMP_MILLISECONDS", "TIMESTAMP_MICROSECONDS", "TIMESTAMP_NANOSECONDS", "CATEGORY", "STRING", };

  public static String name(int e) { return names[e]; }
}

