###
#
# Arguments: CUDA_VER=9.2 or 10.0
#
###
ARG CUDA_VER=10.0

FROM nvidia/cuda:${CUDA_VER}-runtime-ubuntu16.04

#Install java-8, maven, docker image
RUN apt-get update -y && \
    apt-get install -y maven \
    openjdk-8-jdk
