// automatically generated by the FlatBuffers compiler, do not modify

package com.nvidia.spark.rapids.format;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
/**
 * Descriptor for a buffer within another uncompressed buffer.
 */
public final class SubBufferMeta extends Struct {
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public SubBufferMeta __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  /**
   * byte-offset from the start of the buffer where this buffer begins
   */
  public long offset() { return bb.getLong(bb_pos + 0); }
  public void mutateOffset(long offset) { bb.putLong(bb_pos + 0, offset); }
  /**
   * size in bytes of the buffer
   */
  public long length() { return bb.getLong(bb_pos + 8); }
  public void mutateLength(long length) { bb.putLong(bb_pos + 8, length); }

  public static int createSubBufferMeta(FlatBufferBuilder builder, long offset, long length) {
    builder.prep(8, 16);
    builder.putLong(length);
    builder.putLong(offset);
    return builder.offset();
  }
}

