# Copyright (c) 2020, NVIDIA CORPORATION.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: security check

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the branch-0.2 branch
on:
  pull_request_target:
    types: [opened, reopened, synchronize]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: fetch projects
        run: |
          echo ::set-env name=PROJECTS::$(mvn --also-make dependency:tree | grep maven-dependency-plugin | awk '{ out="com.nvidia:"$(NF-1);print out }' | xargs | sed -e 's/ /,/g')        

      - name: Synopsys Detect
        uses: blackducksoftware/github-action@2.0.1
        with:
          args: |
            --blackduck.url="${{ secrets.BLACKDUCK_URL}}" |
            --blackduck.api.token="${{ secrets.BLACKDUCK_API_TOKEN}}" |
            --detect.force.success=true |
            --detect.maven.build.command="-pl='${{ env.PROJECTS }} -am'"
